services:
    postgres:
        container_name: service-postgres
        image: postgres:14
        environment:
          - POSTGRES_DB=miet_video_db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    miet-video-backend-container:
        image: ghcr.io/userver-framework/ubuntu-userver-build-base:v2
        privileged: true
        environment:
          - POSTGRES_DB=miet_video_db
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=password
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/miet_video/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/miet_video:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /miet_video
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
