worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: false

server-port: 8080

miet-video-user-argent: 'miet-video/0.0.1 GNU/Linux 22.04-Ubuntu'

dbconnection: 'postgresql://d_korotov:Votorok228@localhost:5432/miet_video_db'