components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            user-agent: $miet-video-user-agent
            fs-task-processor: fs-task-processor

        orioks-client:
            load-enabled: true
            connection-type: https
            hostname: orioks.miet.ru
            user-agent: miet-video/0.0.1 GNU/Linux 22.04-Ubuntu
            http-timeout: 10s

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
            
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        sessions-manager:
            load-enabled: true
            session-live-time: 1d
        
        users-manager:
            load-enabled: true

        videos-manager:
            load-enabled: true

        lectures-manager:
            load-enabled: true

        comments-manager:
            load-enabled: true

        auth-tokens-manager:
            load-enabled: true
        
        comments-notification-queue:
            load-enabled: true

        registration-handler:                   
            path: /v1/users   
            method: POST                 
            task_processor: main-task-processor

        upload-lecture-handler:                   
            path: /v1/lectures   
            method: POST
            task_processor: main-task-processor

        get-lectures-handler:                   
            path: /v1/lectures 
            method: GET
            task_processor: main-task-processor

        get-lecture-handler:                   
            path: /v1/lectures/{id}
            method: GET
            task_processor: main-task-processor

        authorization-handler:                   
            path: /v1/auth
            method: POST               
            task_processor: main-task-processor

        logout-handler:                   
            path: /v1/logout
            method: POST
            task_processor: main-task-processor

        user-info-handler:                   
            path: /v1/student/info
            method: POST               
            task_processor: main-task-processor

        study-disciplines-handler:
            path: /v1/user/disciplines
            method: POST               
            task_processor: main-task-processor

        add-comment-handler:
            path: /v1/comments
            method: POST               
            task_processor: main-task-processor

        get-comments-handler:
            path: /v1/comments
            method: GET               
            task_processor: main-task-processor

        comments-notify-handler:
            path: /v1/comments/notifications
            method: GET
            task_processor: main-task-processor
            max-remote-payload: 100000
            fragment-size: 100000

        postgres-miet-video-db:
            dbconnection: $dbconnection
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: false
            connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor